$schema: https://git.drupalcode.org/project/drupal/-/raw/10.1.x/core/modules/sdc/src/metadata.schema.json
name: Hero
description: 'Scaler Steps component.'
props:
  type: object
  properties:
    modifier:
      type: string
      title: Modifier
      description: Modifier classes for the header component.
      default: ''
    media:
      type: string
      title: Media
      description: Media content, such as an image or video.
      default: "<img src='./images/hero.png' class='img-fluid rounded' alt='test image' />"
    title:
      type: string
      title: Title
      description: Title text for the header section.
      default: 'Phasellus <strong>auctor</strong>, turpis'
    body_text:
      type: string
      title: Body Text
      description: The body text for the header section.
      default: 'This copy is optional, if nothing is entered nothing will display. Facit nulla in vulputate vulputate aliquam. Commodo esse habent tation nam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sed orci lacus.'
    layout:
      type: string
      title: Layout
      description: Layout setting for the hheaderero component.
      enum:
        - image_top
        - image_bottom
      default: image_top

libraryOverrides:
  dependencies:
    - drupalx_theme/heading
