import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  developSidebar: [{type: 'autogenerated', dirName: 'develop'}],
  testSidebar: [{type: 'autogenerated', dirName: 'test'}],
  administerSidebar: [{type: 'autogenerated', dirName: 'administer'}],
  secureSidebar: [{type: 'autogenerated', dirName: 'secure'}],
  buildSidebar: [{type: 'autogenerated', dirName: 'build'}],
  deploySidebar: [{type: 'autogenerated', dirName: 'deploy'}],
};

export default sidebars;
