<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function conditional_fields_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  // Check if the form ID matches the paragraph type form.
  if ($form_id === 'layout-builder-update-block') {
    // Add a class to the media field wrapper for easier targeting.
    if (isset($form['field_media'])) {
      $form['field_media']['#attributes']['class'][] = 'conditional-media-field';
    }

    // Attach the custom JS library.
    $form['#attached']['library'][] = 'conditional_fields/conditional_fields';
  }
}
