$schema: https://git.drupalcode.org/project/drupal/-/raw/10.1.x/core/modules/sdc/src/metadata.schema.json
name: Breaker
description: 'Breaker component for displaying media and text content full-width.'
props:
  type: object
  properties:
    eyebrow:
      type: string
      title: Eyebrow
      description: Breaker eyebrow text
      default: ''
    title:
      type: string
      title: Title
      description: Breaker title
      default: ''
    media:
      type: string
      title: Media
      description: Breaker image or video markup
      default: ''
    summary:
      type: string
      title: Summary Text
      description: Breaker summary text
      default: ''
    layout:
      type: string
      title: layout
      description: Controls image left/right placement.
      enum:
        - 'left'
        - 'right'
      default: 'left'
    button:
      type: object
      title: Button
      description: Button for the card.
      properties:
        text:
          type: string
          title: Text
          description: The text for the button.
          default: 'Read More'
        url:
          type: string
          title: URL
          description: The link for the button.
          default: '#'
        modifier:
          type: string
          title: Modifier
          description: CSS class modifiers for the button.
          default: 'btn-primary'
    bg_color_modifier:
      type: string
      title: Backgroun Color Modifier
      description: Additional classes for styling the component.
      default: ''

libraryOverrides:
  dependencies:
    - drupalx_theme/heading
