# These lines define the drupalx_theme/global library.
global:
  css:
    # The SMACSS category, "base", is loaded before other categories. Drupal 8/9
    # loads stylesheets based on the SMACSS ordering of:
    # base, layout, component, state, theme
    base:
      dist/css/bootstrap.css: {}
      dist/css/breadcrumbs.css: {}
      dist/css/_variables.css: {}
  dependencies:
    - "drupalx_theme/icons"
    - "drupalx_theme/fonts"

# Included to attach the alerts component css file to status messages.
alerts:
  css:
    component:
      components/alerts/alerts.css: {}

bootstrap-js:
  js:
    //cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js:
      {
        type: external,
        minified: true,
        attributes: { async: true, defer: true },
      }
  dependencies:
  - core/jquery

card:
  css:
    component:
      components/card/card.css: {}

card-group:
  css:
    component:
      components/card-group/card-group.css: {}

custom_search:
  js:
    components/custom_search/js/custom_search.js: {}
  dependencies:
    - core/jquery
    - core/drupal

evidence-report:
  css:
    layout:
      dist/css/evidence-report.css: {}

fonts:
  css:
    component:
      //fonts.googleapis.com/css2?family=Work+Sans:ital,wght@0,400;0,500;0,600;1,400;1,500;1,600&display=swap:
        {
          type: external,
          minified: true,
        }

fonts-secondary:
  css:
    component:
      //fonts.googleapis.com/css2?family=DM+Serif+Text:ital@0;1&display=swap:
        {
          type: external,
          minified: true,
        }

header:
  css:
    component:
      components/header/header.css: {}

header-menu:
  css:
    component:
      components/header-menu/header-menu.css: {}

icons:
  css:
    component:
      //fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&display=swap:
        {
          type: external,
          minified: true,
        }

main-menu:
  css:
    component:
      components/main-menu/main-menu.css: {}

# Included to attach the media component css file with the media component.
media:
  css:
    component:
      components/media/media.css: {}

popover-cdn:
  js:
    //cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js:
      {
        type: external,
        minified: true,
        attributes: {
          async: true,
          defer: true
        },
      }

search-box:
  css:
    component:
      components/search-box/search-box.css: {}

search-results:
  css:
    layout:
      dist/css/search-results.css: {}

site-footer:
  css:
    component:
      components/site-footer/site-footer.css: {}

top-banner:
  css:
    component:
      components/top-banner/top-banner.css: {}

video:
  css:
    component:
      components/video/video.css: {}
